// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCvDXgz3oXSvsTvbWUVlACm-EQwSHEVCo',
    appId: '1:962958553439:web:6d99206cb09d95a5e746ea',
    messagingSenderId: '962958553439',
    projectId: 'mochagatha-45596',
    authDomain: 'mochagatha-45596.firebaseapp.com',
    storageBucket: 'mochagatha-45596.appspot.com',
    measurementId: 'G-7VSBLPMCQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV64FSRt6PW2V--Rjxd2joTv41rFtojvU',
    appId: '1:962958553439:android:18086655fc2f0c9de746ea',
    messagingSenderId: '962958553439',
    projectId: 'mochagatha-45596',
    storageBucket: 'mochagatha-45596.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRWblGCD_jZcQKDDyUSHR23ZI7g2rcbiw',
    appId: '1:962958553439:ios:14a67cdd228b7143e746ea',
    messagingSenderId: '962958553439',
    projectId: 'mochagatha-45596',
    storageBucket: 'mochagatha-45596.appspot.com',
    iosClientId: '962958553439-ot97jpcf3eeqp085eqr3j378qch10gu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRWblGCD_jZcQKDDyUSHR23ZI7g2rcbiw',
    appId: '1:962958553439:ios:14a67cdd228b7143e746ea',
    messagingSenderId: '962958553439',
    projectId: 'mochagatha-45596',
    storageBucket: 'mochagatha-45596.appspot.com',
    iosClientId: '962958553439-ot97jpcf3eeqp085eqr3j378qch10gu2.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
